version: '3.8'

services:

  mysql:
    image: mysql:8
    container_name: tennis-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tennisdb
    ports:
      - "3307:3306"

  app:
    build: .
    container_name: tennis-app
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/tennisdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
